development: &default
  adapter: postgresql
  database: corona_map_development
  encoding: unicode
  host: localhost
  min_messages: warning
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>
  timeout: 5000

test: &test
  <<: *default
  database: corona_map_test
  pool: 5
  reaping_frequency: 10

production:
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>
  timeout: 5000
  url: <%= ENV.fetch("DATABASE_URL", "") %>
